### ISSUE TITLE
Gradle 7: Plugin with id 'maven' not found.

### ISSUE THREAD

**Issue by jasonwilliamson** [seatsio/seatsio-react-native#10]
### Description
Just upgraded React Native to 0.67.4 which bumps up Gradle to 7.2. And now running into this error on build.

`node_modules/@seatsio/seatsio-react-native/android/build.gradle' line: 25

A problem occurred evaluating project ':seatsio_seatsio-react-native'.
> Plugin with id 'maven' not found.`

Maven plugin has been removed in Gradle 7. [docs.gradle.org](https://docs.gradle.org/7.0/userguide/upgrading_version_6.html#removal_of_the_legacy_maven_plugin)

### Steps to Reproduce
1. Upgrade React Native project to React Native 0.67.4
2. Try to build Android Project

**Expected Behaviour:** Builds fine

**Actual Behaviour:** Plugin with id 'maven' not found.

### Versions
"react-native": "0.67.4",
"@seatsio/seatsio-react-native": "^3.1.0",
Gradle 7.2

**Comment by mroloux** [comment]
Hi, we'll have a look.

**Comment by mroloux** [comment]
Should be fixed now, in [v3.2.0](https://github.com/seatsio/seatsio-react-native/releases/tag/v3.2.0)
