### ISSUE TITLE
How to display seat label on seatio map ? 

### ISSUE THREAD

**Issue by mthinh** [seatsio/seatsio-react-native#19]
I would like to display seat label on seatmap like this 
![Screen Shot 2023-01-09 at 8 56 41 AM](https://user-images.githubusercontent.com/28992487/211232387-ced0afdc-ad38-4905-a77c-7f8a3f7dfa26.png)
(this is inside event management where I can toggle show/hide seat label)

But I can't see any config in the document to achieve this, can you please support on this ? 
Thank you

**Comment by mroloux** [comment]
Hi!

You'll need to pass in an `objectLabel` callback:

```jsx
import SeatsioSeatingChart from '@seatsio/seatsio-react-native';

<SeatsioSeatingChart
    region="eu"
    workspaceKey="<yourPublicWorkspaceKey>"
    event="<yourEventKey>"
    objectLabel={object => object.labels.own}
/>
```
