### ISSUE TITLE
Session storage not supported; stored data (e.g. hold token) will be lost after page refresh

### ISSUE THREAD

**Issue by LazloN5** [seatsio/seatsio-react-native#79]
Hi, 

I'm bumping into this issue where it says "The seating chart could not be loaded", I'm not getting any logs why 

I also see _Session storage not supported; stored data (e.g. hold token) will be lost after page refresh_ but the onSessionInitialized isn't doing anything.

I'm using the most basic example:
`<SeatsioSeatingChart
          region="eu"
          workspaceKey="_key_"
          event="_event_"
        />`
        
Anyone else had this issue before?

**Comment by bverbeken** [comment]
This is probably due to a wrong workspace or event key. 
In any case, it's not an issue related to the `seatsio-react-native` package. Please reach out to support@seats.io if you need more help.

**Comment by maazwebook786** [comment]
@LazloN5  did you find any solution for the issue you are facing? I am facing the same issue.

**Comment by LazloN5** [comment]
@maazwebook786 It was indeed a wrong workspace/event key :) So make sure to double check everything
